services:
api:
build: .
ports:
- "8080:8080"
env_file:
- .env
depends_on:
- db
db:
image: postgres:16
environment:
POSTGRES_DB: app
POSTGRES_USER: app
POSTGRES_PASSWORD: app
ports:
  - "5432:5432"
volumes:
 - pgdata:/var/lib/postgresql/data
volumes:
pgdata: {}